//----------------------------------------------------------------------//
//  ___           ___    ___ ___      ___ ___  ________   ________      //
// |\  \         |\  \  /  /|\  \    /  /|\  \|\   ___  \|\   ____\     //
// \ \  \        \ \  \/  / | \  \  /  / | \  \ \  \\ \  \ \  \___|_    //
//  \ \  \        \ \    / / \ \  \/  / / \ \  \ \  \\ \  \ \_____  \   //
//   \ \  \____    \/  /  /   \ \    / /   \ \  \ \  \\ \  \|____|\  \  //
//    \ \_______\__/  / /      \ \__/ /     \ \__\ \__\\ \__\____\_\  \ //
//     \|_______|\___/ /        \|__|/       \|__|\|__| \|__|\_________\//
//              \|___|/                                     \|_________|//
//                                                                      //
//----------------------------------------------------------------------//
//  File            :   Device.cs                                //
//  Description     :                                                   //
//  Original author :   J.Klessens                                      //
//  Company         :   Lyvins                                          //
//  Project         :   LyvinOS                                     //
//  Created on      :   19-3-2014                                        //
//----------------------------------------------------------------------//
//                                                                      //
//  Copyright (c) 2013, 2014 Lyvins                                     //
//                                                                      //
//  Licensed under the Apache License, Version 2.0 (the "License");     //
//  you may not use this file except in compliance with the License.    //
//  You may obtain a copy of the License at                             //
//                                                                      //
//      http://www.apache.org/licenses/LICENSE-2.0                      //
//                                                                      //
//  Unless required by applicable law or agreed to in writing, software //
//  distributed under the License is distributed on an "AS IS" BASIS,   //
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or     //
//  implied. See the License for the specific language governing        //
//  permissions and limitations under the License.                      //
//                                                                      //
//----------------------------------------------------------------------//
//                                                                      //
//  Prerequisites / Return Codes / Notes                                //
//                                                                      //
//----------------------------------------------------------------------//
//                                                                      //
//  Tasks / Features / Bugs                                             //
//                                                                      //
//----------------------------------------------------------------------//


using LyvinDataStoreLib.Models;

namespace LyvinDataStoreLib.LyvinDeviceData.DatabaseHelperObjects
{
    /// <summary>
    /// This class represents an object on the device SQL table
    /// </summary>
    [TableName("device")]
    [PrimaryKey("DeviceID")]
    public class DatabaseHelperDevice
    {
        /// <summary>
        /// Unique identifier generated by the database
        /// </summary>
        public ulong DeviceID { get; set; }

        /// <summary>
        /// Filename of the config file needed by the driver
        /// </summary>
        public string ConfigFile { get; set; }

        /// <summary>
        /// Unique Identifier used by the driver to recognize the device
        /// </summary>
        public string DriverID { get; set; }

        /// <summary>
        /// The filename of the driver
        /// </summary>
        public string DriverFile { get; set; }

        /// <summary>
        /// Indicates the current status of the device
        /// "Active"/"Inactive"/"Removed"/etc.
        /// </summary>
        public string Status { get; set; }

        /// <summary>
        /// The type of the device
        /// </summary>
        public string Type { get; set; }

        public DatabaseHelperDevice()
        {
        }

        /// <summary>
        /// Constructs a device object representing an object on the device SQL table
        /// </summary>
        /// <param name="configFile"></param>
        /// <param name="driverID"></param>
        /// <param name="driverFile"></param>
        /// <param name="status"></param>
        public DatabaseHelperDevice(string configFile, string driverID, string driverFile, string status, string type)
        {
            ConfigFile = configFile;
            DriverID = driverID;
            DriverFile = driverFile;
            Status = status;
            Type = type;
        }
    }
}
